module Colors exposing(colors, getColorByIndex)

import Array

getColorByIndex : List String -> Int -> String
getColorByIndex colorsList index =
  let
      arrayList = Array.fromList colorsList
  in
    case Array.get index arrayList of
      Nothing ->
        "black"
      Just c ->
        c

-- list of html color names
colors : List String
colors =  [ "AliceBlue"
          , "AntiqueWhite"
          , "Aqua"
          , "Aquamarine"
          , "Azure"
          , "Beige"
          , "Bisque"
          , "Black"
          , "BlanchedAlmond"
          , "Blue"
          , "BlueViolet"
          , "Brown"
          , "Burlywood"
          , "CadetBlue"
          , "Chartreuse"
          , "Chocolate"
          , "Coral"
          , "CornflowerBlue"
          , "Cornsilk"
          , "Crimson"
          , "Cyan"
          , "DarkBlue"
          , "DarkCyan"
          , "DarkGoldenrod"
          , "DarkGray"
          , "DarkGreen"
          , "DarkKhaki"
          , "DarkMagenta"
          , "DarkOliveGreen"
          , "DarkOrange"
          , "DarkOrchid"
          , "DarkRed"
          , "DarkSalmon"
          , "DarkSeaGreen"
          , "DarkSlateBlue"
          , "DarkSlateGray"
          , "DarkTurquoise"
          , "DarkViolet"
          , "DeepPink"
          , "DeepSkyBlue"
          , "DimGray"
          , "DodgerBlue"
          , "Firebrick"
          , "FloralWhite"
          , "ForestGreen"
          , "Fuchsia"
          , "Gainsboro"
          , "GhostWhite"
          , "Gold"
          , "Goldenrod"
          , "Gray"
          , "Green"
          , "GreenYellow"
          , "Honeydew"
          , "HotPink"
          , "IndianRed"
          , "Indigo"
          , "Ivory"
          , "Khaki"
          , "Lavender"
          , "LavenderBlush"
          , "LawnGreen"
          , "LemonChiffon"
          , "LightBlue"
          , "LightCoral"
          , "LightCyan"
          , "LightGoldenrodYellow"
          , "LightGray"
          , "LightGreen"
          , "LightPink"
          , "LightSalmon"
          , "LightSeaGreen"
          , "LightSkyBlue"
          , "LightSlateGray"
          , "LightSteelBlue"
          , "LightYellow"
          , "Lime"
          , "LimeGreen"
          , "Linen"
          , "Magenta"
          , "Maroon"
          , "MediumAquamarine"
          , "MediumBlue"
          , "MediumOrchid"
          , "MediumPurple"
          , "MediumSeaGreen"
          , "MediumSlateBlue"
          , "MediumSpringGreen"
          , "MediumTurquoise"
          , "MediumVioletRed"
          , "MidnightBlue"
          , "MintCream"
          , "MistyRose"
          , "Moccasin"
          , "NavajoWhite"
          , "Navy"
          , "OldLace"
          , "Olive"
          , "OliveDrab"
          , "Orange"
          , "OrangeRed"
          , "Orchid"
          , "PaleGoldenrod"
          , "PaleGreen"
          , "PaleTurquoise"
          , "PaleVioletRed"
          , "PapayaWhip"
          , "PeachPuff"
          , "Peru"
          , "Pink"
          , "Plum"
          , "PowderBlue"
          , "Purple"
          , "Red"
          , "RosyBrown"
          , "RoyalBlue"
          , "SaddleBrown"
          , "Salmon"
          , "SandyBrown"
          , "SeaGreen"
          , "Seashell"
          , "Sienna"
          , "Silver"
          , "SkyBlue"
          , "SlateBlue"
          , "SlateGray"
          , "Snow"
          , "SpringGreen"
          , "SteelBlue"
          , "Tan"
          , "Teal"
          , "Thistle"
          , "Tomato"
          , "Turquoise"
          , "Violet"
          , "Wheat"
          , "White"
          , "WhiteSmoke"
          , "Yellow"
          , "YellowGreen"
          ]
